### ISSUE TITLE
Does your package support Vietnamese?

### ISSUE THREAD

**Issue by pvc97** [Steve0929/tiktok-tts#11]
I tried the web version of Tiktok. It can create audio files in Vietnamese language. I don't know what the "Speaker Code" for Vietnamese. Can you help me? Thank you so much.

![image](https://github.com/Steve0929/tiktok-tts/assets/59009078/33f79b39-1488-4931-975f-d79dfd7e7ebb)

**Comment by Steve0929** [comment]
I was unable to get the speaker codes for Vietnamese language on my device, I changed the region code as described here https://github.com/oscie57/tiktok-voice/issues/1#issuecomment-1636107369  but the default English speakers were returned from the TikTok server.

**Comment by Moleys** [comment]
Female: BV074_streaming
Male: BV075_streaming

**Comment by Steve0929** [comment]
Closed with https://github.com/Steve0929/tiktok-tts/pull/14
